---
blank_issues_enabled: false
contact_links:
  - name: NetBox Python Community Support
    url: https://github.com/netbox-community/netbox-python/discussions
    about: Please ask and answer questions here.
